### PR TITLE
Update zoneinfo files to 2020e.

### PR DESCRIPTION
**Pull request by alesapin**
Hello, thank you for this library! We use it to work with timezones in [ClickHouse](https://github.com/ClickHouse/ClickHouse) DBMS. New version (2020e) was recently released https://www.iana.org/time-zones.

Downloaded new Time Zones from https://data.iana.org/time-zones/releases/tzdb-2020e.tar.lz.
Generated data with the following commands:
```
$ cd tzdb-2020e
$ mkdr result
$ make 
$ make DESTDIR=./result install
$ cp -r result/usr/share/zoneinfo/* ../cctz/testdata/zoneinfo/
```

---
This change is [Reviewable](https://reviewable.io/reviews/google/cctz/181)

### CODE REVIEW

**Comment by alesapin** [comment]
@googlebot I signed it!

**Review by devbww — COMMENTED** [review]
Thanks @alesapin, however I already have such a PR in flight that was waiting for reviewers to return from holidays.  I'll send it to you, and we'll see if your approval is enough to allow me to merge.

> Generated data with the following commands:

Note that `testdata/README.zoneinfo` gives a script for how we have been generating these.

**Comment by devbww** [comment]
> I already have such a PR in flight that was waiting for reviewers

The other PR, #182, was merged, so I'll close this.  Thanks again.

**Comment by alesapin** [comment]
`¯\_(ツ)_/¯`

**Pull request closed without merging**
